# Generated by Django 5.1.4 on 2024-12-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_delete_communities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='author',
        ),
        migrations.RemoveField(
            model_name='community',
            name='avatar',
        ),
    ]
