# Generated by Django 5.1.4 on 2024-12-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_remove_community_author_remove_community_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='avatar',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
